# Generated by Django 2.2.5 on 2022-01-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InlineSpeedSkates', '0002_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
